"""Prompting-based detector using a local SmolLM2 instruct model."""

from __future__ import annotations

from typing import Any, cast

import numpy as np
import torch

from .base import StubModelOutput, StubTextDetector


class SmolLMPromptingDetector(StubTextDetector):
    """Prompt-based detector powered by local HuggingFaceTB/SmolLM2-135M-Instruct.

    This model computes the conditional probability of two label strings,
    ``" machine"`` and ``" human"``, given an instruction prompt and input
    text. The machine-label probability is used as the detection score.
    """

    def __init__(
        self,
        model_name: str,
        normalized_scores: bool,
        ood_margin: float,
        seed: int,
        hf_model_id: str = "HuggingFaceTB/SmolLM2-135M-Instruct",
        hf_revision: str = "12fd25f77366fa6b3b4b768ec3050bf629380bac",
    ) -> None:
        super().__init__(model_name, normalized_scores, ood_margin, seed)
        self.hf_model_id = hf_model_id
        self.hf_revision = hf_revision
        self._tokenizer: Any | None = None
        self._model: Any | None = None
        self._device: str = "cpu"

    def _ensure_backend(self) -> None:
        if self._tokenizer is not None and self._model is not None:
            return

        # Imported here rather than at module scope: ``models/__init__`` imports this module
        # eagerly, and transformers costs seconds to import even for runs using other models.
        from transformers import AutoModelForCausalLM, AutoTokenizer

        try:
            self._tokenizer = AutoTokenizer.from_pretrained(self.hf_model_id, revision=self.hf_revision)
            self._model = AutoModelForCausalLM.from_pretrained(self.hf_model_id, revision=self.hf_revision)
        except Exception as exc:  # pragma: no cover
            raise RuntimeError(f"Could not load huggingface model '{self.hf_model_id}'.") from exc

        self._device = "cuda:0" if torch.cuda.is_available() else "cpu"
        model = cast(Any, self._model)
        model.to(self._device)
        model.eval()

    def _build_prompt(self, text: str) -> str:
        return (
            "You are a text-authorship classifier. Decide if the text was written by a human "
            "or generated by an AI assistant. Reply with exactly one word: machine or human.\n\n"
            f"Text:\n{text}\n\nLabel:"
        )

    def _sequence_logprob(self, prompt_ids: Any, candidate_ids: Any) -> float:
        assert self._model is not None
        full_ids = torch.cat([prompt_ids, candidate_ids], dim=1)
        with torch.no_grad():
            logits = self._model(full_ids).logits

        # Predict token i from position i-1; collect only candidate token logprobs.
        token_logprobs = torch.log_softmax(logits[:, :-1, :], dim=-1)
        targets = full_ids[:, 1:]
        gathered = token_logprobs.gather(2, targets.unsqueeze(-1)).squeeze(-1)

        prompt_len = prompt_ids.shape[1]
        cand_logprobs = gathered[:, prompt_len - 1 :]
        return float(cand_logprobs.sum().item())

    def _score_single(self, text: str) -> float:
        self._ensure_backend()
        assert self._tokenizer is not None

        prompt = self._build_prompt(text)
        prompt_ids = self._tokenizer(prompt, return_tensors="pt", add_special_tokens=True).to(self._device).input_ids

        machine_ids = (
            self._tokenizer(" machine", return_tensors="pt", add_special_tokens=False).to(self._device).input_ids
        )
        human_ids = self._tokenizer(" human", return_tensors="pt", add_special_tokens=False).to(self._device).input_ids

        lp_machine = self._sequence_logprob(prompt_ids, machine_ids)
        lp_human = self._sequence_logprob(prompt_ids, human_ids)

        logits = np.array([lp_human, lp_machine], dtype=float)
        logits -= logits.max()
        probs = np.exp(logits)
        probs /= probs.sum()
        return float(probs[1])

    def predict(self, texts: list[str]) -> StubModelOutput:
        scores = np.array([self._score_single(text) for text in texts], dtype=float)
        preds = (scores >= 0.5).astype(int)

        lengths = np.array([len(t) for t in texts], dtype=float)
        ood = (np.abs(scores - 0.5) < self.ood_margin) | (lengths < 40)

        return StubModelOutput(scores=scores, predictions=preds, ood_flags=ood)
